[2025-03-28T16:40:19.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T16:40:19.577+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.generate_air_quality_forecasts scheduled__2025-03-28T16:20:00+00:00 [queued]>
[2025-03-28T16:40:19.588+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.generate_air_quality_forecasts scheduled__2025-03-28T16:20:00+00:00 [queued]>
[2025-03-28T16:40:19.589+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-28T16:40:19.604+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_air_quality_forecasts> on 2025-03-28 16:20:00+00:00
[2025-03-28T16:40:19.613+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_monitoring_v3', 'generate_air_quality_forecasts', 'scheduled__2025-03-28T16:20:00+00:00', '--job-id', '430', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpbvf80taf']
[2025-03-28T16:40:19.615+0000] {standard_task_runner.py:105} INFO - Job 430: Subtask generate_air_quality_forecasts
[2025-03-28T16:40:19.616+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6188) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-28T16:40:19.617+0000] {standard_task_runner.py:72} INFO - Started process 6213 to run task
[2025-03-28T16:40:19.860+0000] {task_command.py:467} INFO - Running <TaskInstance: air_quality_monitoring_v3.generate_air_quality_forecasts scheduled__2025-03-28T16:20:00+00:00 [running]> on host 04906466de51
[2025-03-28T16:40:20.043+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_monitoring_v3' AIRFLOW_CTX_TASK_ID='generate_air_quality_forecasts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T16:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-28T16:20:00+00:00'
[2025-03-28T16:40:20.044+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T16:40:20.106+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-28T16:40:20.109+0000] {data_enriched_predict.py:231} INFO - Chargement des données historiques...
[2025-03-28T16:40:20.166+0000] {data_enriched_predict.py:235} WARNING - Données insuffisantes (8 enregistrements)
[2025-03-28T16:40:20.167+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-28T16:40:20.205+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T16:40:20.206+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=air_quality_monitoring_v3, task_id=generate_air_quality_forecasts, run_id=scheduled__2025-03-28T16:20:00+00:00, execution_date=20250328T162000, start_date=20250328T164019, end_date=20250328T164020
[2025-03-28T16:40:20.233+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T16:40:20.279+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T16:40:20.281+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
