[2025-03-28T20:40:18.138+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T20:40:18.292+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.generate_air_quality_forecasts scheduled__2025-03-28T20:20:00+00:00 [queued]>
[2025-03-28T20:40:18.303+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.generate_air_quality_forecasts scheduled__2025-03-28T20:20:00+00:00 [queued]>
[2025-03-28T20:40:18.303+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-28T20:40:18.318+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_air_quality_forecasts> on 2025-03-28 20:20:00+00:00
[2025-03-28T20:40:18.327+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_monitoring_v3', 'generate_air_quality_forecasts', 'scheduled__2025-03-28T20:20:00+00:00', '--job-id', '466', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpm5qtjdsg']
[2025-03-28T20:40:18.329+0000] {standard_task_runner.py:105} INFO - Job 466: Subtask generate_air_quality_forecasts
[2025-03-28T20:40:18.330+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14033) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-28T20:40:18.330+0000] {standard_task_runner.py:72} INFO - Started process 14060 to run task
[2025-03-28T20:40:18.478+0000] {task_command.py:467} INFO - Running <TaskInstance: air_quality_monitoring_v3.generate_air_quality_forecasts scheduled__2025-03-28T20:20:00+00:00 [running]> on host 04906466de51
[2025-03-28T20:40:18.651+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_monitoring_v3' AIRFLOW_CTX_TASK_ID='generate_air_quality_forecasts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-28T20:20:00+00:00'
[2025-03-28T20:40:18.653+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T20:40:18.707+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-28T20:40:18.710+0000] {data_enriched_predict.py:231} INFO - Chargement des données historiques...
[2025-03-28T20:40:18.765+0000] {data_enriched_predict.py:235} WARNING - Données insuffisantes (44 enregistrements)
[2025-03-28T20:40:18.766+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-28T20:40:18.803+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T20:40:18.804+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=air_quality_monitoring_v3, task_id=generate_air_quality_forecasts, run_id=scheduled__2025-03-28T20:20:00+00:00, execution_date=20250328T202000, start_date=20250328T204018, end_date=20250328T204018
[2025-03-28T20:40:18.827+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T20:40:18.872+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T20:40:18.874+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
