[2025-03-05T11:43:02.998+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T11:43:03.053+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.store_data manual__2025-03-05T11:42:48.312430+00:00 [queued]>
[2025-03-05T11:43:03.068+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.store_data manual__2025-03-05T11:42:48.312430+00:00 [queued]>
[2025-03-05T11:43:03.069+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-05T11:43:03.085+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): store_data> on 2025-03-05 11:42:48.312430+00:00
[2025-03-05T11:43:03.094+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'store_data', 'manual__2025-03-05T11:42:48.312430+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpgu7lr6oj']
[2025-03-05T11:43:03.096+0000] {standard_task_runner.py:105} INFO - Job 146: Subtask store_data
[2025-03-05T11:43:03.097+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T11:43:03.098+0000] {standard_task_runner.py:72} INFO - Started process 82 to run task
[2025-03-05T11:43:03.243+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.store_data manual__2025-03-05T11:42:48.312430+00:00 [running]> on host 6d0e87c01008
[2025-03-05T11:43:03.438+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T11:42:48.312430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T11:42:48.312430+00:00'
[2025-03-05T11:43:03.439+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T11:43:03.461+0000] {data_pipeline.py:149} INFO - Dataframe chargé avec 40 lignes
[2025-03-05T11:43:03.472+0000] {data_pipeline.py:152} INFO - Empty DataFrame
Columns: [city, temperature, humidity, pressure, timestamp, aqi, pm25, pm10]
Index: []
[2025-03-05T11:43:03.518+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-05T11:43:03.558+0000] {data_pipeline.py:172} INFO - Table vérifiée/créée
[2025-03-05T11:43:03.559+0000] {data_pipeline.py:182} INFO - Données insérées avec succès
[2025-03-05T11:43:03.559+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T11:43:03.598+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T11:43:03.599+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=store_data, run_id=manual__2025-03-05T11:42:48.312430+00:00, execution_date=20250305T114248, start_date=20250305T114303, end_date=20250305T114303
[2025-03-05T11:43:03.635+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T11:43:03.694+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T11:43:03.697+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
