[2025-03-27T08:50:06.013+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T08:50:06.080+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_air_quality_dag.fetch_and_save_data scheduled__2025-03-27T08:40:00+00:00 [queued]>
[2025-03-27T08:50:06.099+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_air_quality_dag.fetch_and_save_data scheduled__2025-03-27T08:40:00+00:00 [queued]>
[2025-03-27T08:50:06.100+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-27T08:50:06.124+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_save_data> on 2025-03-27 08:40:00+00:00
[2025-03-27T08:50:06.134+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_air_quality_dag', 'fetch_and_save_data', 'scheduled__2025-03-27T08:40:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpzcq4odtn']
[2025-03-27T08:50:06.136+0000] {standard_task_runner.py:105} INFO - Job 164: Subtask fetch_and_save_data
[2025-03-27T08:50:06.136+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=46) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-27T08:50:06.137+0000] {standard_task_runner.py:72} INFO - Started process 62 to run task
[2025-03-27T08:50:06.461+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_air_quality_dag.fetch_and_save_data scheduled__2025-03-27T08:40:00+00:00 [running]> on host 6d0e87c01008
[2025-03-27T08:50:06.843+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_air_quality_dag' AIRFLOW_CTX_TASK_ID='fetch_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T08:40:00+00:00'
[2025-03-27T08:50:06.845+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T08:50:14.181+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-27T08:50:14.274+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T08:50:14.276+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_air_quality_dag, task_id=fetch_and_save_data, run_id=scheduled__2025-03-27T08:40:00+00:00, execution_date=20250327T084000, start_date=20250327T085006, end_date=20250327T085014
[2025-03-27T08:50:14.345+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T08:50:14.453+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-27T08:50:14.457+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
