[2025-03-28T16:07:32.611+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T16:07:32.655+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_france_pro.init_database scheduled__2025-03-28T15:45:00+00:00 [queued]>
[2025-03-28T16:07:32.666+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_france_pro.init_database scheduled__2025-03-28T15:45:00+00:00 [queued]>
[2025-03-28T16:07:32.667+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-28T16:07:32.682+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): init_database> on 2025-03-28 15:45:00+00:00
[2025-03-28T16:07:32.690+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_france_pro', 'init_database', 'scheduled__2025-03-28T15:45:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmp4skn3hnv']
[2025-03-28T16:07:32.693+0000] {standard_task_runner.py:105} INFO - Job 413: Subtask init_database
[2025-03-28T16:07:32.694+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4730) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-28T16:07:32.695+0000] {standard_task_runner.py:72} INFO - Started process 4755 to run task
[2025-03-28T16:07:32.840+0000] {task_command.py:467} INFO - Running <TaskInstance: air_quality_france_pro.init_database scheduled__2025-03-28T15:45:00+00:00 [running]> on host 04906466de51
[2025-03-28T16:07:33.041+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_france_pro' AIRFLOW_CTX_TASK_ID='init_database' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T15:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-28T15:45:00+00:00'
[2025-03-28T16:07:33.043+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T16:07:33.109+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-28T16:07:33.180+0000] {data_enriched_predict.py:73} INFO - Tables créées avec succès
[2025-03-28T16:07:33.181+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-28T16:07:33.220+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T16:07:33.221+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=air_quality_france_pro, task_id=init_database, run_id=scheduled__2025-03-28T15:45:00+00:00, execution_date=20250328T154500, start_date=20250328T160732, end_date=20250328T160733
[2025-03-28T16:07:33.272+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T16:07:33.326+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-28T16:07:33.328+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
